module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#a43700",
        secondary: "#a93700",
        "primary-container": "#cd4800",
        "on-primary-container": "#fffbff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#1a1c1c",
        "on-secondary-fixed": "#380d00",
        "surface-container": "#eeeeee",
        "outline-variant": "#dfc0b5",
        "on-primary-fixed": "#380d00",
        outline: "#8b7268",
        "on-secondary-fixed-variant": "#812800",
        "on-tertiary-container": "#fdfcfc",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "tertiary-container": "#747575",
        "inverse-surface": "#2f3131",
        "on-tertiary-fixed-variant": "#464747",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "on-error-container": "#93000a",
        "secondary-fixed": "#ffdbcf",
        "inverse-primary": "#ffb59a",
        "on-primary-fixed-variant": "#802a00",
        "surface-container-highest": "#e2e2e2",
        "secondary-fixed-dim": "#ffb59b",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-surface-variant": "#574239",
        "surface-container-low": "#f3f3f4",
        "surface-dim": "#dadada",
        "surface-variant": "#e2e2e2",
        "surface-tint": "#a83900",
        "secondary-container": "#fd7039",
        "surface-bright": "#f9f9f9",
        "primary-fixed": "#ffdbcf",
        "on-secondary-container": "#601c00",
        "inverse-on-surface": "#f0f1f1",
        tertiary: "#5b5c5c",
        background: "#f9f9f9",
        "tertiary-fixed": "#e3e2e2",
        "on-primary": "#ffffff",
        "on-surface": "#1a1c1c",
        surface: "#f9f9f9",
        "tertiary-fixed-dim": "#c7c6c6",
        "on-background": "#1a1c1c",
        "primary-fixed-dim": "#ffb59a"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        xl: "48px",
        sm: "16px",
        md: "24px",
        lg: "32px",
        gutter: "20px",
        base: "4px",
        xs: "8px",
        margin: "24px"
      },
      fontFamily: {
        body: ["Hanken Grotesk", "sans-serif"],
        headline: ["Manrope", "sans-serif"],
        display: ["Manrope", "sans-serif"],
        label: ["Hanken Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
